// Generated by tools/make_zodiac.py. Don't edit by hand.
// Star positions and figures: d3-celestial, BSD 3-Clause, Copyright (c) 2015 Olaf Frohn.

/// A constellation of the zodiac, for the Zodiac widget.
struct ZodiacSign: Identifiable {
    let key: String
    let name: String
    let symbol: String
    let element: String
    /// The first and last day the sun is in the sign, as month and day.
    let first: (Int, Int)
    let last: (Int, Int)
    /// The name of its brightest named star.
    let brightest: String
    /// Each star as x, y (0...1 across a square, north up) and its magnitude.
    let stars: [Double]
    /// The figure: each line is a run of star numbers.
    let lines: [[Int]]

    var id: String { key }
}

extension ZodiacSign {
    /// In order from Aries.
    static let all: [ZodiacSign] = [
        ZodiacSign(
            key: "aries", name: "Aries", symbol: "♈\u{FE0E}", element: "Fire",
            first: (3, 21), last: (4, 19), brightest: "Hamal",
            stars: [0.130, 0.262, 3.6, 0.682, 0.499, 2.0, 0.853, 0.650, 2.6, 0.870, 0.738, 3.9],
            lines: [[0, 1, 2, 3]]),
        ZodiacSign(
            key: "taurus", name: "Taurus", symbol: "♉\u{FE0E}", element: "Earth",
            first: (4, 20), last: (5, 20), brightest: "Aldebaran",
            stars: [0.130, 0.333, 3.0, 0.460, 0.461, 0.9, 0.501, 0.477, 3.4, 0.551, 0.483, 3.6, 0.534, 0.437, 3.8, 0.502, 0.398, 3.5, 0.211, 0.165, 1.6, 0.662, 0.556, 3.4, 0.856, 0.614, 3.7, 0.649, 0.710, 3.9, 0.870, 0.630, 3.6, 0.804, 0.835, 4.3],
            lines: [[0, 1, 2, 3, 4, 5, 6], [3, 7, 8, 9], [8, 10, 11]]),
        ZodiacSign(
            key: "gemini", name: "Gemini", symbol: "♊\u{FE0E}", element: "Air",
            first: (5, 21), last: (6, 20), brightest: "Pollux",
            stars: [0.870, 0.485, 3.3, 0.803, 0.489, 2.9, 0.625, 0.403, 3.1, 0.404, 0.219, 4.4, 0.225, 0.153, 1.6, 0.130, 0.287, 1.2, 0.202, 0.333, 4.1, 0.323, 0.518, 3.5, 0.458, 0.571, 4.0, 0.688, 0.718, 1.9, 0.625, 0.847, 3.4, 0.336, 0.716, 3.6],
            lines: [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [7, 11]]),
        ZodiacSign(
            key: "cancer", name: "Cancer", symbol: "♋\u{FE0E}", element: "Water",
            first: (6, 21), last: (7, 22), brightest: "Tarf",
            stars: [0.303, 0.771, 4.3, 0.433, 0.533, 3.9, 0.446, 0.406, 4.7, 0.418, 0.130, 4.0, 0.697, 0.870, 3.5],
            lines: [[0, 1, 2, 3], [1, 4]]),
        ZodiacSign(
            key: "leo", name: "Leo", symbol: "♌\u{FE0E}", element: "Fire",
            first: (7, 23), last: (8, 22), brightest: "Regulus",
            stars: [0.749, 0.682, 1.4, 0.752, 0.559, 3.5, 0.673, 0.482, 2.0, 0.348, 0.458, 2.6, 0.130, 0.592, 2.1, 0.340, 0.588, 3.3, 0.691, 0.390, 3.4, 0.826, 0.318, 3.9, 0.870, 0.372, 3.0],
            lines: [[0, 1, 2, 3, 4, 5, 0], [2, 6, 7, 8]]),
        ZodiacSign(
            key: "virgo", name: "Virgo", symbol: "♍\u{FE0E}", element: "Earth",
            first: (8, 23), last: (9, 22), brightest: "Spica",
            stars: [0.870, 0.389, 4.0, 0.853, 0.469, 3.6, 0.736, 0.510, 3.9, 0.646, 0.523, 2.7, 0.527, 0.592, 4.4, 0.463, 0.686, 1.0, 0.252, 0.600, 4.1, 0.144, 0.594, 3.9, 0.559, 0.314, 2.9, 0.587, 0.441, 3.4, 0.423, 0.508, 3.4, 0.310, 0.472, 4.2, 0.130, 0.467, 3.7],
            lines: [[0, 1, 2, 3, 4, 5, 6, 7], [8, 9, 3], [4, 10, 11, 12]]),
        ZodiacSign(
            key: "libra", name: "Libra", symbol: "♎\u{FE0E}", element: "Air",
            first: (9, 23), last: (10, 22), brightest: "Zubeneschamali",
            stars: [0.578, 0.707, 3.2, 0.701, 0.376, 2.8, 0.474, 0.130, 2.6, 0.310, 0.326, 3.9, 0.310, 0.811, 3.6, 0.299, 0.870, 3.7],
            lines: [[0, 1, 2, 3, 4, 5], [1, 3]]),
        ZodiacSign(
            key: "scorpio", name: "Scorpio", symbol: "♏\u{FE0E}", element: "Water",
            first: (10, 23), last: (11, 21), brightest: "Antares",
            stars: [0.858, 0.334, 2.9, 0.857, 0.222, 2.3, 0.826, 0.130, 2.6, 0.699, 0.302, 2.9, 0.639, 0.326, 1.1, 0.591, 0.381, 2.8, 0.491, 0.575, 2.3, 0.480, 0.695, 3.0, 0.466, 0.833, 3.6, 0.363, 0.865, 3.3, 0.217, 0.870, 1.9, 0.142, 0.787, 3.0, 0.168, 0.748, 2.4, 0.214, 0.681, 1.6],
            lines: [[0, 1, 2], [1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]]),
        ZodiacSign(
            key: "sagittarius", name: "Sagittarius", symbol: "♐\u{FE0E}", element: "Fire",
            first: (11, 22), last: (12, 21), brightest: "Kaus Australis",
            stars: [0.731, 0.683, 3.1, 0.703, 0.618, 1.8, 0.732, 0.501, 2.7, 0.701, 0.382, 2.8, 0.794, 0.276, 3.8, 0.401, 0.870, 4.0, 0.389, 0.773, 4.0, 0.496, 0.491, 2.6, 0.595, 0.418, 3.2, 0.240, 0.816, 4.1, 0.193, 0.650, 4.4, 0.186, 0.414, 4.7, 0.294, 0.367, 4.6, 0.361, 0.353, 5.0, 0.420, 0.371, 4.9, 0.540, 0.398, 2.0, 0.814, 0.525, 3.0, 0.471, 0.433, 3.3, 0.484, 0.278, 3.8, 0.453, 0.259, 2.9, 0.404, 0.207, 4.9, 0.378, 0.179, 3.9, 0.376, 0.130, 4.5, 0.527, 0.262, 3.5, 0.548, 0.305, 4.9],
            lines: [[0, 1, 2, 3, 4], [5, 6, 7, 8, 3], [9, 10, 11, 12, 13, 14, 15, 8, 2, 16, 1, 7, 17, 15, 18, 19, 20, 21, 22], [18, 23, 24, 15]]),
        ZodiacSign(
            key: "capricorn", name: "Capricorn", symbol: "♑\u{FE0E}", element: "Earth",
            first: (12, 22), last: (1, 19), brightest: "Deneb Algedi",
            stars: [0.870, 0.258, 4.3, 0.839, 0.334, 3.0, 0.770, 0.435, 4.8, 0.624, 0.687, 4.1, 0.579, 0.742, 4.1, 0.304, 0.591, 3.8, 0.130, 0.384, 2.9, 0.187, 0.399, 3.7, 0.333, 0.398, 4.3, 0.467, 0.409, 4.1],
            lines: [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0]]),
        ZodiacSign(
            key: "aquarius", name: "Aquarius", symbol: "♒\u{FE0E}", element: "Air",
            first: (1, 20), last: (2, 18), brightest: "Sadalsuud",
            stars: [0.870, 0.505, 3.8, 0.850, 0.494, 4.7, 0.688, 0.425, 2.9, 0.537, 0.328, 3.0, 0.466, 0.347, 3.9, 0.434, 0.322, 3.6, 0.405, 0.324, 4.0, 0.329, 0.459, 3.7, 0.219, 0.490, 4.4, 0.267, 0.702, 3.7, 0.532, 0.571, 4.3, 0.488, 0.461, 4.2, 0.450, 0.298, 4.8, 0.210, 0.686, 4.0, 0.130, 0.649, 4.8],
            lines: [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [2, 10], [3, 11], [5, 12], [13, 8, 14]]),
        ZodiacSign(
            key: "pisces", name: "Pisces", symbol: "♓\u{FE0E}", element: "Water",
            first: (2, 19), last: (3, 20), brightest: "Alpherg",
            stars: [0.342, 0.350, 4.7, 0.356, 0.261, 4.5, 0.324, 0.306, 4.7, 0.348, 0.409, 4.7, 0.262, 0.503, 3.6, 0.200, 0.606, 4.3, 0.130, 0.710, 3.8, 0.164, 0.705, 4.6, 0.214, 0.669, 4.5, 0.261, 0.660, 4.8, 0.330, 0.638, 5.2, 0.375, 0.633, 4.3, 0.435, 0.639, 4.4, 0.643, 0.649, 4.0, 0.724, 0.668, 4.1, 0.773, 0.652, 4.3, 0.804, 0.668, 5.0, 0.818, 0.702, 3.7, 0.779, 0.739, 5.0, 0.717, 0.733, 4.5, 0.698, 0.705, 5.0, 0.870, 0.690, 4.5],
            lines: [[0, 1, 2, 0, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 14], [17, 21]]),
    ]
}
